### ISSUE TITLE
While writing my own fitness function, it returns before executing whole function.

### ISSUE THREAD

**Issue by MuhammadNafyKhan** [PonyGE/PonyGE2#102]
I have written grammar for my neural network having 3 layers (1 input,1 hidden-layer,1 output layer).
But as I writes fitness function for that grammar then it returns before executing whole function.

**Comment by jmmcd** [comment]
That doesn't happen with any other fitness function, so we'll need some details and code to demonstrate the problem.

**Comment by MuhammadNafyKhan** [comment]
Grammar File
<start> ::= sig(<sum>+<weight>) -- sig(<sum>+<weight>) -- sig(<sum>+<weight>) -- sig(<sum>+<weight>) -- sig(<sum>+<weight>) --- <hidden-layers> --- sig(<sum>+<weight>)
<hidden-layers> ::= <hidden-layers> --- <layer> |  <layer> | <hidden-layers> --- <hidden-layers> 
<layer> ::= <layer> -- sig(<sum>+<weight>) | sig(<sum>+<weight>)
<sum> ::= mul(<weight>,<features>) | <sum>+<sum>
<weight> ::= <digit>.<digit><digit> | -<digit>.<digit><digit>
<digit> ::= 0|1|2|3|4|5|6|7|8|9
<features> ::= x[0]|x[1]|x[2]|x[3]|x[4]|x[5]

**Comment by MuhammadNafyKhan** [comment]
Fitness Function 


 def evaluate(self, ind, **kwargs):
        """
        Default fitness execution call for all fitness functions. When
        implementing a new fitness function, this is where code should be added
        to evaluate target phenotypes.
        
        There is no need to implement a __call__() method for new fitness
        functions which inherit from the base class; the "evaluate()" function
        provided here allows for this. Implementing a __call__() method for new
        fitness functions will over-write the __call__() method in the base
        class, removing much of the functionality and use of the base class.
                
        :param ind: An individual to be evaluated.
        :param kwargs: Optional extra arguments.
        :return: The fitness of the evaluated individual.
        """
        
        # Evaluate the fitness of the phenotype
        print("In NN.py  File\n")
        #print("self : ",self,"\n")       
        #print("Before Replacement ",ind,"\n")
        #print("kwargs : ",kwargs,"\n")
        training_in, training_out, test_in, test_out=get_data(params['DATASET_TRAIN'], params['DATASET_TEST'])
        #print(training_in.shape)

        training_in=training_in.transpose()
        training_out=training_out.transpose()
        test_in=test_in.transpose()
        test_out=test_out.transpose()
        #print("Train data shape ",training_in.shape)
        train_data_size=np.size(training_in,0)
        #print(training_in)
        phenotype=ind.phenotype
        output=np.zeros((train_data_size,1))



        for i in range(0,train_data_size):
            #print("before\n",phenotype)
            phenotype=phenotype.replace("x[0]", "training_in["+str(i)+"][0]")   
            phenotype=phenotype.replace("x[1]", "training_in["+str(i)+"][1]")
            phenotype=phenotype.replace("x[2]", "training_in["+str(i)+"][2]")
            phenotype=phenotype.replace("x[3]", "training_in["+str(i)+"][3]")
            phenotype=phenotype.replace("x[4]", "training_in["+str(i)+"][4]")
            phenotype=phenotype.replace("x[5]", "training_in["+str(i)+"][5]")
            print("After Replacement\n",phenotype)
            layers_output=0
            splited=phenotype.split("---")
            total_layers=phenotype.count("---")+1 
            print("total layers = ",total_layers,"\n")

            for j in range(0, total_layers):
                
                Neurons=splited[j].count("--")
                Neurons+=1
                print("Neurons in layer-",j," ::",Neurons,"\n")
                subsplited=splited[j].split("--")
                #print("subsplited\n",subsplited)
                temp=layers_output
                layers_output=0

                for kl in range(0, Neurons):

                    #print("Neurons=",Neurons,"\n")
                    print("\nNeuron : ",kl,"\n")  
                    print((subsplited[kl])[:len(subsplited[kl])-2] +  "+"+str(temp)+")")
                    layers_output=layers_output+eval( (subsplited[kl])[:len(subsplited[kl])-2] +  "+"+str(temp)+")")
                   

            print(training_in[i,:],"Output :: ",layers_output)
            i=0
            input(i)
        print(type(ind.phenotype))
        fitness = eval(ind.phenotype)
        
        return fitness

**Comment by MuhammadNafyKhan** [comment]
Above given code is not complete, but I am wondering that why for loops are not executed properly.
It returns to calling file, from where evaluate function was called, before executing for loops completely.

**Comment by MuhammadNafyKhan** [comment]
Just focus on for loops.

**Comment by jmmcd** [comment]
"input(i)" - You are asking the user to enter a number inside the fitness function and then discarding it?

Can you paste a complete individual phenotype (before doing any replace() calls)?

"print(type(ind.phenotype))" -- I think you're telling us that you don't see the output of this line when you run?

**Comment by MuhammadNafyKhan** [comment]
I took input delibarately to look whether it reaches to this point or not.
sometime it stops for input but many times it does not take inputs and for loops are not executed completely.

**Comment by MuhammadNafyKhan** [comment]
sig(mul(-6.67,training_in[0][5])+mul(3.46,training_in[0][3])+mul(-7.40,training_in[0][0])+5.59) -- sig(mul(6.97,training_in[0][2])+0.42) -- sig(mul(1.89,training_in[0][0])+mul(-5.66,training_in[0][0])+mul(8.29,training_in[0][3])+mul(-3.34,training_in[0][3])+9.23) -- sig(mul(-6.41,training_in[0][4])+mul(-4.82,training_in[0][2])+mul(0.08,training_in[0][2])+-8.44) -- sig(mul(-3.93,training_in[0][0])+-5.88) --- sig(mul(-3.12,training_in[0][0])+-3.49) --- sig(mul(-0.18,training_in[0][1])+mul(6.83,training_in[0][1])+mul(7.49,training_in[0][4])+9.19)

**Comment by MuhammadNafyKhan** [comment]
given above is phenotype.
'--' is used to separate between neurons and '---' is used to separate between layers.

**Comment by MuhammadNafyKhan** [comment]
I also have one other query that how can I pass on information from one layer to other in neural network given above phenotype.

**Comment by jmmcd** [comment]
I can think of two main possibilities:

1. The fitness function starts, but doesn't finish. That could happen if there is an error inside the code, throwing an Exception, which is caught here: https://github.com/PonyGE/PonyGE2/blob/06b1a8cafb90196af8507b50c380fdf978bb68fa/src/fitness/base_ff_classes/base_ff.py#L37

2. The fitness function doesn't even start. This could happen if the individual is identical to a previous one, and then the fitness is just looked up in a cache, depending on a setting here: https://github.com/PonyGE/PonyGE2/blob/06b1a8cafb90196af8507b50c380fdf978bb68fa/src/algorithm/parameters.py#L168

> I also have one other query that how can I pass on information from one layer to other in neural network given above phenotype.

This is really a Python programming question, not PonyGE. I would recommend to prototype your network idea separately before putting it into PonyGE. By that I mean write a function which given a phenotype, creates the corresponding network and runs it.
