### ISSUE TITLE
Start computation again using previous population

### ISSUE THREAD

**Issue by noeldum** [PonyGE/PonyGE2#103]
How can we start computation again using previous population

Is this possible? 

Are all genomes saved somewhere to use as initialisation for the new start?

Great project. Thank you!

**Comment by dvpfagan** [comment]
You can save the inds and seed a separate run with them

https://github.com/PonyGE/PonyGE2/wiki/Seeding#re-creating-ponyge2-runs

**Comment by noeldum** [comment]
Thanks. On the [same page](https://github.com/PonyGE/PonyGE2/wiki/Seeding) the chapter titled
2. Seeding runs with one or more target solutions
is closer to what I am looking for.
