### ISSUE TITLE
Using Mapper, Grammar and Tree.py

### ISSUE THREAD

**Issue by eeub03** [PonyGE/PonyGE2#106]
Hey, not sure if this is the right place, but I am currently implementing another Genetic Programming algorithm in Python that is very similar to Grammatical Evolution. Would I be able to use your Mapper, Grammar and Tree files in this implementation? I will make sure to give credit where due

**Comment by jmmcd** [comment]
Yes, certainly. PonyGE is licensed under GPL version 3.
