### ISSUE TITLE
PonyGE2 installation in Python

### ISSUE THREAD

**Issue by bonorico** [PonyGE/PonyGE2#107]
Dear Dev Team,
first of all thanks a lot for setting up this repo. 
Possibly you will excuse the following question, if it is too trivial, but I could not find explicit instructions about installation of  PonyGE2 in Python ....
I could only assume, maybe some of these approaches might work:

1) pip3 install git+git:"git repo"

2) git clone "git repo"
     sudo python3 setup.py install

3) Other method ?

Thanks for any suggestion or clarification on that matter

**Comment by dvpfagan** [comment]
You check out the code
And then run it via the terminal. There is a running experiments section on
the Wiki.

Dave
