### ISSUE TITLE
Im facing difficulties in understanding classification results

### ISSUE THREAD

**Issue by Danielgol** [PonyGE/PonyGE2#113]
What kind of values do I need to use for dataset's classes?
I was trying to see how ponyge works and tried to change some values in banknote's dataset (changed classes value from -1 to 0, because I've found the same dataset in the web in this form -> classes' values 0 and 1) and I've got a huge difference between the fitness fuction before and after the change I've made.

Do I need to specify my changes in the grammar of something like that? I mean, what do I need to change in future datasets that I'm gonna test to make things work well?

Thanks :)

**Comment by jmmcd** [comment]
Hi Daniel,

By default our classification uses the f1_score as the fitness function. As you can see here we convert the real values that come from the GE individual to booleans: https://github.com/PonyGE/PonyGE2/blob/06b1a8cafb90196af8507b50c380fdf978bb68fa/src/utilities/fitness/error_metric.py#L88

So, effectively we are assuming that the true y labels are also boolean, ie {0, 1}, not {-1, 1}.

James

**Comment by jmmcd** [comment]
Re-reading your issue -- when you changed the csv, you changed it from {-1, 1} -> {0, 1}, right? With the `f1_score` error metric, I guess that should have improved fitness, is that what you saw?

But I see we also have a `hinge_loss` which seems to assume {-1, 1} class labels. 

Scikit-learn allows for both conventions, and others. 

Probably the right solution is for each error metric to convert real numbers to labels according to its own convention, and assert that `y_true` is in the same convention. Then at least any mismatch would throw an error immediately.

**Comment by Danielgol** [comment]
Hi @jmmcd, thanks for your help!!! :)

"I guess that should have improved fitness, is that what you saw?", Yes, exactly!!!
The best one with {-1,1} classes had it's fitness around 0.37, while the best one with {0,1} classes had it's fitness around 0.9.
First I thought I should declare my classes' values in the grammar (but it seems that ponyge does it automaticly with the values in the dataset). But when I saw those results I got lost. I was like, what values should I use? Then I thought probably the value "0" should be interfering in the fitness results, but I was not sure.

**Comment by jmmcd** [comment]
Hi Danielgol see the latest commit. You should be able to use both `f1_score` and `hinge` successfully, whether the data file has {-1, 1} or {0, 1}. Please let us know if anything goes wrong.

(Note hinge loss is to be minimized and in my tests with `hinge`, on the Banknote dataset, I saw mean hinge loss ~ 0.1, corresponding to a raw accuracy of 93%.)

**Comment by Danielgol** [comment]
Perfect! The results are way more similar now (both around 90% accuracy)

Just one last question. I was just using binary classes for my tests, but can ponyge deal with multiclass datasets for classification? Using 3, 4 and more classes?

Again, thank you!!! :)

**Comment by jmmcd** [comment]
We don't have any examples for multi class.

One easy/ugly hack would be to define some numerical ranges corresponding to each class, eg [-inf, -1] -> class -1, [-1, 1] -> class 0, [1, inf] -> class 1. 

A better approach sometimes used in GP is to create one tree/expression per class, and eg take the one with largest output as the prediction. That would be easy to implement, and a pull request would be welcome!

James
