### ISSUE TITLE
Grammars with if statements

### ISSUE THREAD

**Issue by epris** [PonyGE/PonyGE2#115]
Hello to everybody,

I have defined a grammar with if statements. The condition of the if statements takes into account the features of each sample in the dataset.
In order to evaluate each individual on the dataset i changed the method "evaluate" in the fitness class as follow
          

            x = self.training_in
            yhat = []
            p, d = ind.phenotype, {'np': np}
            for i in range(x.shape[1]):
                d['x'] = x[:, i]
                exec(p, d)
                y_prev =  d['XXXeval_or_exec_outputXXX']
                assert np.isrealobj(y_prev)
                yhat.append(y_prev)
            yhat = np.array(yhat)`
The execution is now very slow because I have to iterate over all the samples for each individual in the population. 
Is there another solution, faster than the one I have proposed?

Best regards

**Comment by jmmcd** [comment]
I guess that an alternative would be `d['x'] = x`, rewrite the grammar so that `p` is able to process the entire dataset (not just one column at a time), and remove the loop. But I don't know what `p` looks like or how the `if`-statements relate to this.

**Comment by epris** [comment]
Hi @jmmcd,
thank you for your response.

The original version of ponyge2 allows to process the entire dataset and it uses d['x'] = x as you are suggesting but my problem is that my grammar can generate rules like
if(np.less(x[1],10):
 //do something
else:
//do things

I get errors because if-statement cannot process the entire dataset  because some samples will satisfy the condition other no.

**Comment by laure-crochepierre** [comment]
To generate if statements, I would insert `np.where` function in the grammar (and import NumPy in a custom fitness class )
Ex : A rule could be `np.where(<if>,<then>,<else>)`with <if>  a boolean np.array generated from operations on the initial dataset. You could use np.less(x[1],10) in here I think. 

Also, to avoid errors at evaluation time, I inserted a try-except loop (useful if some conditions filter out everything and leave us with an empty array to evaluate )

I hope it helps!

**Comment by dvpfagan** [comment]
You could also make use of compile() and get you grammar to define the
content of a function that you can then evaluate

https://realpython.com/python-eval-function/

Dave

**Comment by jmmcd** [comment]
Yes, compiling before passing to `eval` will help a bit as it will make things a bit faster as it removes part of the overhead. But yes, using `np.where` is key.
