### ISSUE TITLE
Why aren't parameters saved in JSON files (or similar formats)?

### ISSUE THREAD

**Issue by nbro** [PonyGE/PonyGE2#118]
Parameters are specified in text files, which is like the rawest possible file format that you could use to solve this problem. JSON files or similar formats should probably be preferred over plain text files, because they allow a hierarchical/structural representation of the parameters and their values.

**Comment by dvpfagan** [comment]
Yes, I agree JSON would be more beneficial.

Again we are more than happy for this type of improvement to come from the
wider community via pull requests.

When we get around to doing a new release I'm sure we will use the open
issues as a guide for features to add.

Thanks
Dave

**Comment by nbro** [comment]
@dvpfagan Ok, what happens if I contribute to this project? Will I be included in the list of contributors and authors, including in the license? [You're using GPL, so I guess so (although I don't remember the details)](https://opensource.stackexchange.com/a/4582/698). I would like to be acknowledged (i.e. officially be part of the authors/contributors) if I contribute to this project.

**Comment by dvpfagan** [comment]
@jmmcd thoughts on this? Do we add a contributors section to the readme on the main page? Should we have something in the code explicitly giving credit to people? Should we add @nbro as a member to the project upon a successful pull request?

**Comment by nbro** [comment]
@dvpfagan I opened an issue specifically targetting the "license & authors" issue: https://github.com/PonyGE/PonyGE2/issues/122, so we may just talk about it there.

**Comment by jmmcd** [comment]
Changing from plain text to JSON for parameter files would be easy but would not provide any benefit *unless* we actually took advantage of (eg) the hierarchy. But that would require rethinking and reworking a lot of parameter-handling code. I don't think we should pursue this unless we see a strong example where plain-text can't do the job.

**Comment by nbro** [comment]
@jmmcd JSON or other file formats may provide more flexibility in the future. I'm not saying that this should be done immediately, but it looks like text files aren't really the right tool for this job. Moreover, it shouldn't be so difficult to change the code. I can do it myself, after someone accepts my latest pull request: https://github.com/PonyGE/PonyGE2/pull/121.

**Comment by jmmcd** [comment]
As I said, I would need a more convincing case than possible future flexibility. I don't think a PR on this will be accepted.

**Comment by nbro** [comment]
@jmmcd One advantage of using JSON (or similar formats) is that there are tools that parse JSON and beautify them, so make all files look consistent. With your current setup, it's not possible, unless you write your own beautifier. This is one of the advantages. The other is that configurations' values are really only used for certain parts of package/process, so we could have a hierarchical definition of the configurations, if we wanted. This does not mean we will do this.

**Comment by jmmcd** [comment]
We really don't need a tool to pretty-print the current colon-separated format.
