### ISSUE TITLE
PonyGE2 should be compliant with pep8

### ISSUE THREAD

**Issue by nbro** [PonyGE/PonyGE2#119]
After having dived a little into the source, I immediately found classes with identifiers like this `my_class`. Why? In Python, classes should use `CamelCase`. Any particular reason why `my_class` was used, or were you just careless?

**Comment by dvpfagan** [comment]
Yeah, hold our hands up there, certainly a little lax with the code review
in places it would appear.

Again we were using pep-8 checkers in our IDE's during the initial dev of
the project but over time it does appear that some issues have crept in.

Another thing to add to the list for future releases

Dave

**Comment by nbro** [comment]
@dvpfagan This pull request https://github.com/PonyGE/PonyGE2/pull/121 fixes some of the issues. Please, take a look at it and let me know what needs to be changed for it to be accepted.

**Comment by jmmcd** [comment]
The PR above has been merged, but in general we should continue to be careful with PEP8.
