### ISSUE TITLE
The documentation of how to write grammars needs to be improved

### ISSUE THREAD

**Issue by nbro** [PonyGE/PonyGE2#123]
After having read [the Wiki page on grammars](https://github.com/PonyGE/PonyGE2/wiki/Grammars), I know what BNF grammars are and more or less how they are parsed in PonyGE2, but not everything that is possible to do is explained there. You explain there how to dynamically or compactly write ranges of integers, but you do not explain many other things that one may want to do or that are already being done in the examples of the grammars that you provide. For instance, I've seen that some grammars, such as [this](https://github.com/PonyGE/PonyGE2/blob/master/grammars/supervised_learning/Vladislavleva4.bnf), use Python functions or functions that are imported from external libraries/packages (in this linked case, the NumPy's function `np.sin`, and others, are being used). 

So, how does the BNF grammar know how to parse these tokens? So, apparently, we can use custom functions (non-terminals) and maybe even terminals that will be later written in Python (or the language that we are using), but **how** and **where** are we supposed to write these functions (that we use to specify the grammar)? Where will they be passed or used?

**Comment by mikefenton** [comment]
All of those modules / imports / function definitions should be imported/defined in the fitness function, as this is where the fitness is evaluated/executed.

**Comment by nbro** [comment]
@mikefenton Could please be more specific? For example, in the case of the grammar I linked above, [`Vladislavleva4.bnf`](https://github.com/PonyGE/PonyGE2/blob/master/grammars/supervised_learning/Vladislavleva4.bnf), it uses, for example, `plog`. I don't seem to find any `plog` function inside any of the modules in `src/fitness/supervised_learning`.

**Comment by mikefenton** [comment]
Look at line 6 of `src/fitness/supervised_learning/supervised_learning.py` you'll see the import there:

https://github.com/PonyGE/PonyGE2/blob/master/src/fitness/supervised_learning/supervised_learning.py#L6

**Comment by nbro** [comment]
@mikefenton Global imports are almost never a good thing (one of the reasons is because of what just happened). If you accept my other pull request, I may decide to fix these issues too.

**Comment by jmmcd** [comment]
I think this is one case where `from x import *` is well-justified, as it allows us to define a function in our base class without importing it explicitly.

Agreed, improved documentation on this was needed. I've added a short section to the wiki on this: https://github.com/PonyGE/PonyGE2/wiki/Grammars
