### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by MarkusEvo** [PonyGE/PonyGE2#124]
Which requirements are essential? I was wondering if one could run ponyge2 without scikit-learn, scipy, pandas and matplotlib. So it could maybe be implemented with pypy.

**Comment by dvpfagan** [comment]
Unfortunately you need all the libraries.

Dave

**Comment by nbro** [comment]
@MarkusEvo The requirements are specified here: https://github.com/PonyGE/PonyGE2/blob/master/requirements.txt. However, you will get an error if you just do `pip install -r requirements.txt`. This pull request https://github.com/PonyGE/PonyGE2/pull/121 fixes the issue, but it's not yet been accepted.

**Comment by jmmcd** [comment]
I think for some possible applications it would not be hard to remove all of these dependencies, eg just don't call the `moo_` plotting functions, comment out the imports. I don't think we will attempt that in this repo as we are firmly in the Numpy/Scipy stack like most of this ecosystem.

A better hope is that PyPy will support all these things someday soon. It already supports Numpy so there is hope.

**Comment by MarkusEvo** [comment]
Thank you for your help, that answered my question. Which modules exactly do use scipy and pandas?

**Comment by jmmcd** [comment]
Hi @MarkusEvo, probably it's easiest for you to check the top of the modules you're interested in!

**Comment by MarkusEvo** [comment]
I already implemented it in pypy, you just have to comment out the plotting and imports in stats.py. Disable Error Metric and just don't use moo.

**Comment by MarkusEvo** [comment]
Well now I'm having a memory leak issue instead, there is probably something that relies on reference counting which I wasn't able to identify yet
