### ISSUE TITLE
Saving Individuals

### ISSUE THREAD

**Issue by MarkusEvo** [PonyGE/PonyGE2#125]
Hey, I was wondering if or how I could save individuals above a certain fitness x. Just like the best individual.

**Comment by laure-crochepierre** [comment]
Hi, I would probably filter `individuals` var in `stats.stats.get_stats` [(here)](https://github.com/PonyGE/PonyGE2/blob/facf8302c15423b5172e834ea6a3319ed68be170/src/stats/stats.py#L45). If I'm correct,  `individuals` is a list of instances of the Class `Individual` [(here)](https://github.com/PonyGE/PonyGE2/blob/facf8302c15423b5172e834ea6a3319ed68be170/src/representation/individual.py#L7) and each individual has a `fitness` attribute. 

I would add an output to `get_stats` : 
```
if end == False : 
    return None 
else : 
    return  [ind for ind in individuals if ind.fitness > your_threshold]
````
And you can save the created list directly from your main file.

**Comment by MarkusEvo** [comment]
Thank you!
