### ISSUE TITLE
Codon initialization with low CODON_SIZE values

### ISSUE THREAD

**Issue by LBannenberg** [PonyGE/PonyGE2#128]
From a GE theoretical perspective, the lowest sane setting for the CODON_SIZE parameter should be the number of options in the largest production. For example, in [Banknote.bnf](https://github.com/PonyGE/PonyGE2/blob/master/grammars/supervised_learning/Banknote.bnf) the largest production has 8 different options, so setting CODON_SIZE to any number >= 8 makes sense.

However, if you do that, you get a crash during initialization because in [derivation.py](https://github.com/PonyGE/PonyGE2/blob/master/src/representation/derivation.py) codons are initialized in a random range that starts just above that:

```
codon = randrange(productions['no_choices'],
                      params['BNF_GRAMMAR'].codon_size,
                      productions['no_choices']) + prod_index
```

[on line 51](https://github.com/PonyGE/PonyGE2/blob/master/src/representation/derivation.py#L51)
[on line 232](https://github.com/PonyGE/PonyGE2/blob/master/src/representation/derivation.py#L232)
[on line 339](https://github.com/PonyGE/PonyGE2/blob/master/src/representation/derivation.py#L339)

So in the case of the last rule of banknote, codons can only be initialized within [8, CODON_SIZE] instead of [0, CODON_SIZE].

Why is this? Is this a mistake?

If you change this to:
`codon = randrange(start=0, stop=params['BNF_GRAMMAR'].codon_size, step=productions['no_choices']) + prod_index`

Then you can simply set the CODON_SIZE to the minimum sane value and don't get any errors.

**Comment by jmmcd** [comment]
I don't agree that the minimum sane value is the number of options in the largest rule, as that would often give an unintended bias on other rules. For me the minimum sane value is the lowest common multiple of the numbers of productions in all rules. Most people avoid thinking about this by just setting a large number, eg 1000 :) 

But if someone did want to use the LCM in this way, they could still see the crash you have seen, so a fix is still needed here. 

I'm not sure of the original motivation or the `step=productions[no_choices]` idea so I hope someone else can help here.

**Comment by LBannenberg** [comment]
I should have phrased that better - I meant that the absolute minimum to not have a degenerate run with unreachable productions would be to set codon size to the size of the largest production rule. I don't think that's a particularly good value to set it at, and I'm currently working on some experiments to figure out just how sensitive GE actually is to tweaking this number. That's how I bumped into this issue in the first place - I need to be able to experiment with bottom of the barrel values :)

I looked a bit longer at my proposed change and I think I found an error. Here's a snippet demonstrating in isolation what I think is the better approach:

```
import random

codon_size = 20
choice_indices = [0, 1, 2]
no_choices = len(choice_indices)
highest_seen = 0
lowest_seen = 2 * codon_size
results = set()

for i in range(10000):
    chosen_production = random.choice(choice_indices)  # corresponds to line 46, 50
    codon = random.randrange(start=0, stop=codon_size - no_choices + 1, step=no_choices)  + chosen_production  # corresponds to line 51
    results.add(codon)

print(sorted(results))
```

If you try this with choice_indices = [0, 1, 2] and [0, 1, 2, 3] you can see that it generates an equal number of different encodings for each choice, but always stays under codon_size like it should. The step size isn't actually different from the code as it already exists, it's just the start and ending of the randrange that are more robust to unusual CODON_SIZE settings.

So my proposed change is to turn the aforementioned lines into: 

```
codon = randrange(start=0, stop=params['BNF_GRAMMAR'].codon_size - productions['no_choices'] + 1, step=productions['no_choices']) + prod_index
```

**Comment by jmmcd** [comment]
I understand the argument for `start=0`, though I don't know why this wasn't used in the first place. 

I understand your original argument for `stop=params['BNF_GRAMMAR'].codon_size` also. 

I think the "error" you mentioned is that we could create a codon larger than CODON_SIZE, thanks to the ` + prod_index`. Right?

If so, I think I understand the argument for `stop=params['BNF_GRAMMAR'].codon_size - productions['no_choices'] + 1`. 

It's possible we'll hear a reason why it wasn't `start=0` in the first place. Let's wait til next week and then I would welcome a pull request, if you have tested the proposed change. Thanks!

**Comment by dvpfagan** [comment]
As the above arguments states yes the upper guard is definitely wrong :D

The fix proposed for that is wost welcome,

The starting from the number of productions rather than zero, might be to
force some degeneracy into the genotype but again looking at it now further
down the line I see no reason why it can't be 0

James I would say we are able to accept a pull request for this

Dave

**Comment by LBannenberg** [comment]
I've created a pull request [here](https://github.com/PonyGE/PonyGE2/pull/132).

**Comment by LBannenberg** [comment]
Hey :)

Did you need any further info or test cases to act on the pull request?

**Comment by jmmcd** [comment]
Thanks again!
