### ISSUE TITLE
GP+EM review PonyGE2

### ISSUE THREAD

**Issue by wblangdon** [PonyGE/PonyGE2#134]
Hi,
    The September 2021 issue of "Genetic Programming and Evolvable Machines" has
a review of PonyGE2 https://doi.org/10.1007/s10710-021-09409-5
Do feel free to use it, but do please credit the journal as the source.
Bill

        Prof. W. B. Langdon
        Department of Computer Science
        University College London
        Gower Street, London WC1E 6BT, UK
        http://www.cs.ucl.ac.uk/staff/W.Langdon/

GP EM                  http://www.springer.com/10710
EuroGP 2022            http://www.evostar.org/2022/eurogp/
barracuda_0.7.107h     http://seqbarracuda.sourceforge.net/
choose your background http://web4.cs.ucl.ac.uk/staff/W.Langdon/colour_telephone/bgcolor.html
A Field Guide to Genetic Programming
                       http://www.gp-field-guide.org.uk/
GP Bibliography        http://gpbib.cs.ucl.ac.uk/
[Vu2021_Article_SoftwareReviewPonyGE2.pdf](https://github.com/PonyGE/PonyGE2/files/7038247/Vu2021_Article_SoftwareReviewPonyGE2.pdf)

**Comment by jmmcd** [comment]
Added a note to wiki. Thanks again!

**Comment by wblangdon** [comment]
Thanks James.
It helps the journal too

Bill
