### ISSUE TITLE
Need to fill out the documentation

### ISSUE THREAD

**Issue by mikefenton** [PonyGE/PonyGE2#17]
We need to fill out the documentation as much as possible. For those of us using PyCharm we should follow the standard function documentation template they provide. Simply type """ (three "s) and press enter and it will auto-complete the doc template for you, complete with params for inputs and returns. We should try to fill these out as completely as possible for EVERY function in the whole program. 

The Readme file also needs to be as verbose as possible. I've structured and arranged it to make it as readable as possible, but we still need to give a full runthrough of the entire program and the various relationships between the different functions in it. People completely new to the whole area should be able to understand the entire program by going through the readme and the documentation for the various functions.

**Comment by mikefenton** [comment]
Mutation file now fully commented and documented correctly. Will update this thread as the documentation for individual files is completed.

**Comment by mikefenton** [comment]
Selection file now fully commented and documented correctly. Readme updated accordingly.

**Comment by mikefenton** [comment]
Replacement file now fully commented and documented correctly.

**Comment by mikefenton** [comment]
Search_loop and step now fully commented and documented correctly.

**Comment by mikefenton** [comment]
Utilities.initialise_run now fully commented and documented correctly.

**Comment by mikefenton** [comment]
All operator files now fully commented and documented correctly. All operator files also now streamlined and cleaned up to make the code more readable and understandable. Unnecessary functions moved or removed.

**Comment by codykenb** [comment]
Anyone using Python 3.4? I got what looked like circular dependency errors with 3.4. These errors disappeared after upgrade to 3.5.2

Might be related "Circular imports involving relative imports are now supported" https://docs.python.org/3/whatsnew/3.5.html

**Comment by dvpfagan** [comment]
Yeah we need to say py3.5.2 is the version that it works with

**Comment by mikefenton** [comment]
I've updated the python version checker to check that at least python 3.5 is being used.

representation.grammar.py now fully commented and documented correctly.
representation.tree.py now fully commented and documented correctly.

**Comment by mikefenton** [comment]
All algorithm files now fully commented and documented correctly.
All fitness files now fully commented and documented correctly.

Remaining files are in stats and utilities folders.

**Comment by mikefenton** [comment]
All stats files now fully commented and documented correctly.

**Comment by mikefenton** [comment]
`utilities.algorithm`, `utilities.stats`, and `utilities.representation` all now fully commented and documented correctly. 

THE ONLY REMAINING FILES TO COMMENT AND DOCUMENT ARE IN `UTILITIES.FITNESS`.



(....and the `README`, of course).

**Comment by mikefenton** [comment]
`README` has been filled out down as far as `Evaluation`. Still so much left to add...

**Comment by mikefenton** [comment]
`README` has been nearly completed. The only remaining files left to comment/document are:

1. `fitness.python_script_evaluation.py`
2. `fitness.progsys.py`
3. `fitness.sequence_match.py`

These files are visually a bit of a mess, I don't know what they're doing so can't comment/document them; i'll leave that up to the authors themselves.

Remaining files which are nearly completely commented/documented:

4. `utilities.fitness.baselines.py`
5. `utilities.fitness.optimize_constants.py`

These last two I have taken a stab at documenting and commenting but there is some weirdness going on, particularly with `baselines.py`. Some functions don't use their imports, some use variables that aren't locally defined within the function (i.e. defined from outside the scope). Also, what is the purpose of the `baselines.py` file?

**Comment by t-h-e** [comment]
`fitness.python_script_evaluation.py` is a copy from https://github.com/t-h-e/HeuristicLab.CFGGP and will not be changed in any way to avoid maintenance problems.

`fitness.progsys.py` has been transformed from a *visually a bit of a mess* to a pretty PEP8 confrom file with sparkling sprinkles on top ;) https://github.com/jmmcd/PonyGE2/commit/f7dba8cca915da18b4ef91ae6443e3520bb92e1a

`README` entry for program synthesis has been added. https://github.com/jmmcd/PonyGE2/commit/2d09e82c1ee0368fefe5fe33a764eb55d0885149

**Comment by mikefenton** [comment]
Wiki and Documentation extensively expanded, and nearing completion (until new functionality is added, that is). A few things remaining that have caught my eye:

1. Constant optimisation is not documented in the Wiki. @jmmcd would you be able to put something together for that?
2. The Hill Climbing algorithms are not documented in the Wiki (although the functions themselves look fairly well commented). @jmmcd could you take a look again? Might be a simple enough copy-and-paste from the existing function docstrings. Not sure where they belong; scripts or example problems?
    - On the subject of the hill climbers, do we have an example implementation of them? There's no example parameters file or anything (again, not sure if they're scripts or example problems). Seeing as we have them there it would be good to have some sort of working example, along with the documentation required for people to tap in to them themselves.

If you get a chance, could everyone have a thorough dig through the wiki? The more in-depth, the better. Things to note:
1. What's missing?
2. What's wrong/incorrect?
3. What's broken (e.g. broken links)?

Having lists of the above will allow us to finish this off ASAP. The idea is to have the whole thing wrapped up into the next release version before GECCO. The code is pretty much done (save a few TODOs and a general code review), but the Wiki remains...

**Comment by jmmcd** [comment]
I've written a little about constant optimisation and about hill-climbing.

**Comment by mikefenton** [comment]
Documentation is never truly "done" _per se_, but everything is now fully commented, every function now has a full docstring, and the wiki probably takes a full day to read. Any new/changed functionality should be fully commented and documented when introduced, and the wiki should be maintained from here on out. Closing this issue as it's a maintenance issue from here on out.
