### ISSUE TITLE
We should create a PonyGE2-specific email address

### ISSUE THREAD

**Issue by mikefenton** [PonyGE/PonyGE2#76]
Rather than listing our personal contact email addresses on the Wiki and in the README, we should create a PonyGE2-specific email address. Perhaps host it from NCRA?

**Comment by jmmcd** [comment]
We should also create a PonyGE2 "organisation". This would give us the URL GitHub.com/ponyge2/ponyge2 rather than GitHub.com/jmmcd/ponyge2.

**Comment by mikefenton** [comment]
PonyGE2 Inc? Ltd? PonyGE2 & Sons?

**Comment by dvpfagan** [comment]
This might do the redirect trick
https://help.github.com/articles/redirects-on-github-pages/

**Comment by jmmcd** [comment]
We've transferred from jmmcd/PonyGE2 to PonyGE2/PonyGE2.

We decided not to create an email address, but just tell users to interact via the Github issues list.

**Comment by mikefenton** [comment]
Update: We're now at PonyGE/PonyGE2
