### ISSUE TITLE
Getting started with default sample problem 

### ISSUE THREAD

**Issue by sirsh** [PonyGE/PonyGE2#77]
Greetings Ponies

I have tried to get started with the sample. I've cloned latest and run with defaults (regression problem).
Straight away I run into issues, being a newbie. Please confirm that the defaults work in latest build on clean fetch.

When i run with defaults, the sample crashes because *some* individuals seem to have a Null genome which causes the mutation code to crash here due to incomparable  types _Int_ and _None_

`if params['WITHIN_USED']:
        eff_length = min(len(ind.genome), ind.used_codons)`

I can sweep my problem under the carpet with the following but I dont know what is the intended behaviour here.

`eff_length = min(len(ind.genome), ind.used_codons) if ind.used_codons != None else len(ind.genome)`

I am running with Anaconda, Python 3.5+ and would greatly appreciate some help getting the basics up and running as per the README.

Cheers,

sirsh

**Comment by mikefenton** [comment]
Hi Sirsh,

Thanks for getting in touch! We actually just found this issue this morning, I'll be committing a fix in the next hour or so. The issue is related to invalid individuals getting "None" attributes set. 

Thanks!

**Comment by sirsh** [comment]
Ok, great thanks.
Symptoms cropped up in stats too for the same reason. But I guess when you fix it at the root, all be well.
Ill keep digging.
Cheers,
s

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mikefenton** [comment]
Sorted now. Thanks for taking the time to comment!
