### ISSUE TITLE
Distributed MultiAgent implementation

### ISSUE THREAD

**Issue by aadeshnpn** [PonyGE/PonyGE2#78]
Hello PonyGE2 developer team. 
I am working on online GE algorithm for Multi-agent system. I have already implemented it using Ponyge earlier version. I want to port my implementation to this PonyGE2 version as well and I have started working on a new branch. After completion, would you merge my implementation into the main branch?

**Comment by dvpfagan** [comment]
If you can add it in such a way that it doesn't touch the core components
of the code base, I would say we would deffinitly consider merging it at a
later date after some code review.

Dave

**Comment by mikefenton** [comment]
Hi Aadesh,

Sounds interesting! If you submit a pull request with the code integrated with PonyGE2, then we can take a look and take it from there. As Dave mentioned, the most important things for us are:
1. The proposed code is cleanly, concisely, and simply integrated with the main PonyGE2 code base (functionality and ease of use is key with the PonyGE2 project!),
2. The proposed code does not impede on the core components of the PonyGE2 code base,
3. The proposed code is well tested,
4. The proposed code is PEP-8 compliant,
5. The proposed code is completely commented and documented

If all of the above points are met, then we'd be more than happy to include your work!

Regards,

Michael

**Comment by aadeshnpn** [comment]
Thank you.
I have tried to follow the instructions that you have mentioned. My changes are now ready. I don't have permission to create a branch on this repo in order to put pull request.

**Comment by dvpfagan** [comment]
Can you link us to the code so we can review it? Can you not fork your own
copy of ponyge from github?

Dave

**Comment by aadeshnpn** [comment]
Thanks Dave.
I have made a fork of ponyge and submitted a pull request to the main repo.

**Comment by mikefenton** [comment]
Hi Aadesh,

Can you put together detailed and thorough documentation for the Wiki on this new implementation?

Regards,

Michael

**Comment by aadeshnpn** [comment]
Sure Mike.
I will update the Wiki in coming days

**Comment by dvpfagan** [comment]
Once the wiki is updated we can close this

**Comment by mikefenton** [comment]
You can either add the relevant info to the [Search Options](https://github.com/PonyGE/PonyGE2/wiki/Search-Options) page or you can post it directly here and we can incorporate it into the wiki.

**Comment by aadeshnpn** [comment]
I can post here and you can incorporate it into the wiki.

**Distributed Search Option**
In the standard implementation, GE runs on a single machine or agent which has access to all the individuals in the population. Then it can choose among the highest performing individuals from the population to perform genetic operations. In a multi-agent implementation, each agent has its own instance of genetic information. An agent can only have access to its own genotype. The agent moves in an environment and communicates to nearby agents to share the genetic information. After collection genetic information from a handful of agents, it can apply the genetic operations by itself for the information that it has gathered.

**Distributed Search Loop**
When MULTIAGENT parameter is passed as True, search_loop and step methods from algorithm.distributed_algorithm gets activated. The first step in distributed search loop is to initialized agents object. Based on the parameter set for AGENT_SIZE that the number of agents is created where INTERATION_PROBABILITY parameter is passed while initializing agents. This parameter defines the probability of interaction with other agents. Higher this value, there are higher changes interacting with other agents and higher chances of finding solutions faster. Then after initializing agents, for each generation, step module is called which takes the list of agents as a function parameter and returns a list of agents.

**Distributed Step**         
In this module, for each agent in the environment, the agent will perform: sense, act and update action sequentially. These three action or modules are built in for the agents. These modules can be extended or overridden based on the type of agent required to solve a particular problem. After performing these actions

**Agent**
It is the class that defines the behavior of the agents. Right now we have only defined a very primitive agent but based on the requirements the method of this class can be overridden. The Sense method describes the way the agent gets information from the environment. The Act method provides a way from the agent to process the information obtained from Sense method. The update method is agent's way to update its state. In our case, the Sense method is used to find other nearby agents, the Act method is used to apply genetic operations to the stack of genetic information collected from nearby agents and the update method is used to update the agent's genetic information.

**Comment by mikefenton** [comment]
The Distributed Step information appears to be incomplete. Can you provide the rest of the text?
