### ISSUE TITLE
Evaluation on Training and Test Data

### ISSUE THREAD

**Issue by roestabiten** [PonyGE/PonyGE2#87]
Hi,

I've tried but doesnt succeed to use the post-run evaluation "training_test". How do I activate this attribute?

**Comment by jmmcd** [comment]
Hi roestabiten, thanks for the query and sorry for the delay!

By default, in (eg) the regression problem there is only a training dataset. If you tell PonyGE2 to use a test dataset, it will internally activate `training_test`. Try this command line:

`python ponyge.py --population_size 10 --generations 10 --dataset_test "Vladislavleva4/Test.txt"`
