### ISSUE TITLE
Error on Grammars page

### ISSUE THREAD

**Issue by buddha314** [PonyGE/PonyGE2#97]
The [Grammar Page](https://github.com/PonyGE/PonyGE2/wiki/Grammars) appears to contain the error

```
s = "def print_arg(arg):{:print(arg:}print_arg("Hello")"
```

that should read

```
s = "def print_arg(arg):{:print(arg):}print_arg("Hello")"
```

Note `(arg` vs `(arg)`

**Comment by jmmcd** [comment]
Fixed thanks!
